
/**************************************************************
 *	
 *	battleMusic, 8 bit, 11025Hz,
 *	1 channel, 1599744 bytes/channel
 *	Total Size: 1 * 1599744 + 4 (header) = 1599788 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/obecerra/Desktop/Space Game/battleMusic.wav
 *	Time-stamp: Fri Apr 26 10:44:24 2019
 *	
 **************************************************************/

#ifndef __BATTLEMUSICH__
#define __BATTLEMUSICH__

#define BATTLEMUSICFREQ 11025
#define BATTLEMUSICLEN 1599744

extern const unsigned char battleMusic[1599744];

#endif /* __BATTLEMUSICH__ */
