
/**************************************************************
 *	
 *	bruh, 8 bit, 11025Hz,
 *	1 channel, 13312 bytes/channel
 *	Total Size: 1 * 13312 + 4 (header) = 13356 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/obecerra/Desktop/Space Game/bruh.wav
 *	Time-stamp: Fri Apr 26 10:52:33 2019
 *	
 **************************************************************/

#ifndef __BRUHH__
#define __BRUHH__

#define BRUHFREQ 11025
#define BRUHLEN 13312

extern const unsigned char bruh[13312];

#endif /* __BRUHH__ */
