
/**************************************************************
 *	
 *	humanMusic, 8 bit, 11025Hz,
 *	1 channel, 198504 bytes/channel
 *	Total Size: 1 * 198504 + 4 (header) = 198548 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/obecerra/Desktop/Space Game/humanMusic.wav
 *	Time-stamp: Thu Apr 18 22:11:19 2019
 *	
 **************************************************************/

#ifndef __HUMANMUSICH__
#define __HUMANMUSICH__

#define HUMANMUSICFREQ 11025
#define HUMANMUSICLEN 198504

extern const unsigned char humanMusic[198504];

#endif /* __HUMANMUSICH__ */
