
/**************************************************************
 *	
 *	mapMusic, 8 bit, 11025Hz,
 *	1 channel, 982528 bytes/channel
 *	Total Size: 1 * 982528 + 4 (header) = 982572 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/obecerra/Desktop/Space Game/mapMusic.wav
 *	Time-stamp: Fri Apr 26 10:44:55 2019
 *	
 **************************************************************/

#ifndef __MAPMUSICH__
#define __MAPMUSICH__

#define MAPMUSICFREQ 11025
#define MAPMUSICLEN 982528

extern const unsigned char mapMusic[982528];

#endif /* __MAPMUSICH__ */
