
/**************************************************************
 *	
 *	shopMusic, 8 bit, 11025Hz,
 *	1 channel, 559616 bytes/channel
 *	Total Size: 1 * 559616 + 4 (header) = 559660 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/obecerra/Desktop/Space Game/shopMusic.wav
 *	Time-stamp: Fri Apr 26 10:45:12 2019
 *	
 **************************************************************/

#ifndef __SHOPMUSICH__
#define __SHOPMUSICH__

#define SHOPMUSICFREQ 11025
#define SHOPMUSICLEN 559616

extern const unsigned char shopMusic[559616];

#endif /* __SHOPMUSICH__ */
