
/**************************************************************
 *	
 *	punch, 8 bit, 11025Hz,
 *	1 channel, 5069 bytes/channel
 *	Total Size: 1 * 5069 + 4 (header) = 5113 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/obecerra/Desktop/Space Game/punch.wav
 *	Time-stamp: Thu Apr 18 22:27:26 2019
 *	
 **************************************************************/

#ifndef __PUNCHH__
#define __PUNCHH__

#define PUNCHFREQ 11025
#define PUNCHLEN 5069

extern const unsigned char punch[5069];

#endif /* __PUNCHH__ */
